### ISSUE TITLE
rabbitmq example is not longer deployable with latest node.js buildpacks

### ISSUE THREAD

**Issue by rmey** [IBM-Cloud/clouddatabases-helloworld-examples#5]
-----> Installing binaries
          engines.node (package.json): 8.x
          engines.npm (package.json): unspecified (use default)
          **ERROR** Unable to install node: no match found for 8.x in [10.18.1 10.19.0 12.16.0 12.16.1]
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
Need to fix node version in package.json

**Comment by drpalaric** [comment]
Thanks. Updated to the latest supported Node version.
